### PR TITLE
slideshow reappear

### PR DESCRIPTION
**Pull request by Ananthavijay**
### Submission Checklist

- [x] Your pull request targets the `master` branch of the repository.
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] You have read the [Contributing guidelines](https://github.com/jboss-outreach/gci/blob/master/CONTRIBUTING.md) and your changes follow them.

#### Type of Change

- [x] Bug fix
- [ ] New implementation

### PR Description

This will make the slideshow appear again.
ping @KeenWarrior

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
@KeenWarrior Are we going to merge #128 ?

**Comment by aashutoshrathi** [comment]
@Ananthavijay always make sensible PR titles and commit messages as per https://github.com/JBossOutreach/gci.jbossoutreach.org/blob/master/CONTRIBUTING.md

**Comment by divyanshkul** [comment]
@Ananthavijay As the contributing guidelines [here](https://github.com/JBossOutreach/gci.jbossoutreach.org/blob/master/CONTRIBUTING.md) read, the standard way to fix a bug is to first make a descriptive issue, describing everything and then later referring that issue number in your PR.

**Comment by KeenWarrior** [comment]
thanks @Ananthavijay  🎉

**Pull request merged**
